// generated by stringer -type=Sampler -output=types_string.go; DO NOT EDIT

package controlplane

import "fmt"

const _Sampler_name = "RandomSamplerCustomerSamplerDriverSamplerDeviceSamplerSessionSampler"

var _Sampler_index = [...]uint8{0, 13, 28, 41, 54, 68}

func (i Sampler) String() string {
	if i < 0 || i+1 >= Sampler(len(_Sampler_index)) {
		return fmt.Sprintf("Sampler(%d)", i)
	}
	return _Sampler_name[_Sampler_index[i]:_Sampler_index[i+1]]
}
