// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/api-proxy/proto/api/api.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_api is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/api-proxy/proto/api/api.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_api

import proto "github.com/HailoOSS/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Request struct {
	Path             *string         `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Verb             *string         `protobuf:"bytes,2,req,name=verb" json:"verb,omitempty"`
	Get              []*Request_Pair `protobuf:"bytes,3,rep,name=get" json:"get,omitempty"`
	Post             []*Request_Pair `protobuf:"bytes,4,rep,name=post" json:"post,omitempty"`
	Header           []string        `protobuf:"bytes,5,rep,name=header" json:"header,omitempty"`
	Body             *string         `protobuf:"bytes,6,opt,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Request) GetVerb() string {
	if m != nil && m.Verb != nil {
		return *m.Verb
	}
	return ""
}

func (m *Request) GetGet() []*Request_Pair {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetPost() []*Request_Pair {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Request) GetHeader() []string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

type Request_Pair struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request_Pair) Reset()         { *m = Request_Pair{} }
func (m *Request_Pair) String() string { return proto.CompactTextString(m) }
func (*Request_Pair) ProtoMessage()    {}

func (m *Request_Pair) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Request_Pair) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Response struct {
	StatusCode       *int32   `protobuf:"varint,1,req,name=statusCode" json:"statusCode,omitempty"`
	Header           []string `protobuf:"bytes,2,rep,name=header" json:"header,omitempty"`
	Body             *string  `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetStatusCode() int32 {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return 0
}

func (m *Response) GetHeader() []string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func init() {
}
